Generate SAS token for storage container access

diff --git a/builds/service/service-deployment.yaml b/builds/service/service-deployment.yaml
--- a/builds/service/service-deployment.yaml
+++ b/builds/service/service-deployment.yaml
@@ -38,7 +38,6 @@ jobs:
       azureSubscription: $(az.subscription)
       keyVaultName: $(az.keyVault)
       secretsFilter: >-
-        TestBlobStoreSas,
         TestContainerRegistryPassword,
         TestEventHubCompatibleEndpoint,
         TestIotHubConnectionString,
@@ -59,6 +58,51 @@ jobs:
       allowPartiallySucceededBuilds: true
       itemPattern: core-linux/artifactInfo.txt
 
+  - task: AzureCLI@2
+    displayName: Get SAS URI for Blob Storage Account
+    inputs:
+      azureSubscription: $(az.subscription)
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        resource_group='EdgeBuilds'
+        storage_account='e2eteststorageedge'
+        container_name='e2etest'
+
+        # Set expiry time for the SAS token
+        expiry_time="$(date --utc --date "+2 days" +"%Y-%m-%dT%H:%MZ")"
+
+        # Generate the SAS token for the container
+        sasToken=$(
+          az storage container generate-sas \
+            --account-name "$storage_account" \
+            --name "$container_name" \
+            --https-only \
+            --expiry "$expiry_time" \
+            --as-user \
+            --auth-mode login \
+            --permissions drwl \
+            --output tsv
+        )
+
+        if [ $? -ne 0 ]; then
+          echo "Failed to generate SAS token."
+          exit 1
+        fi
+
+        echo "SAS token for Azure Storage container acquired, expires $expiry_time"
+
+        # Construct the SAS URI
+        endpoint=$(
+          az storage account show \
+            --name "$storage_account" \
+            --resource-group "$resource_group" \
+            --query 'primaryEndpoints.blob' \
+            --output tsv
+        )
+        sasUri="$endpoint$container_name?$sasToken"
+        echo "##vso[task.setvariable variable=TestBlobStoreSas;issecret=true]$sasUri"
+  
   - pwsh: |
       $certsDir = '$(System.ArtifactsDirectory)/certs'
       New-Item "$certsDir" -ItemType Directory -Force | Out-Null
